language: scala
scala:
- 2.12.4
- 2.11.12
jdk:
- oraclejdk8
notifications:
  email:
  - truffaut.julien@gmail.com
script:
  - sbt ++$TRAVIS_SCALA_VERSION newts${TARGET}/$PRE
  - sbt ++$TRAVIS_SCALA_VERSION newts${TARGET}/test packageSrc
env:
  matrix:
    - TARGET=JVM PRE=test:compile
    - TARGET=JS  PRE=test:fastOptJS
sudo: true
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_install:
 - export PATH=${PATH}:./vendor/bundle
install:
  - rvm use 2.4.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1
after_success:
- '[[ $TRAVIS_BRANCH == "master" && "${TRAVIS_PULL_REQUEST}" == "false" ]] && { sbt +publish ghpagesPushSite; };'
